### ISSUE TITLE
FireBase와 DB 이용에 관하여.

### ISSUE THREAD

**Issue by RE-A** [pm-tool-se2019/Source#1]
https://firebase.google.com/docs/database/admin/start/

1. Firebase 문서를 읽어보면, 서버쪽에서도 관리자 계정을 통해 접근 제어 설정이나 계정 관리 등등이 필요합니다. 이 부분은 누가 어떻게 다뤄지나요? 일반 이용자들은 그냥 제한된 권한으로 사용하면 되나요?

2. FIrebase에 데이터를 업로드 하려면 user 등록을 해야 하는 것 같은데, 이 부분은 어떻게 처리해야 할까요? 직접 프로그램 안에 user 등록 기능까지 구현해야 하는지, 아니면 일괄적으로 관리자 측에서 id를 발급해서 배분하는 식으로 처리하나요?

**Comment by yusa-imit** [comment]
1. 데이터베이스 스키마 관리는 관리자 계정을 이용해서 하게 됩니다. 일반 유저들은 발급된 O-Auth Key를 이용해서 데이터에 대한 추가/수정/삭제 권한만 가지게 됩니다. 스키마 추가가 필요하시면 저한테 문의 주시면 됩니다. 

2. user등록은 계획상으로 2주차 이후에 필요할 것 같습니다. 아마 이것도 O-Auth 인증으로 바로 가능할 것 같은데. 아마 관리자측에서 따로 id 발급해서 배분받으신 다음 API사용하는것처럼 처리하시면 될 것 같습니다. 아직은 유저등록은 구현하실 필요 없습니다.

**Comment by RE-A** [comment]
네 알겠습니다. 답변 감사합니다!
