### ISSUE TITLE
FireBase API Key Issue

### ISSUE THREAD

**Issue by RE-A** [pm-tool-se2019/Source#8]
Firebase를 각 클라이언트가 사용하려면 DB의 URL과 API key를 알아야 합니다. URL은 공개적인 정보고, API key가 30글자 언저리의 무작위 영숫자로 이루어진 key로 비밀번호 같은 역할을 합니다. 이 두가지 정보가 있으면 누구든 데이터베이스를 검색하고 조작할 수 있습니다.

 요 정보를 각 클라이언트가 받아야 하는데, 이 전달 방법에 조금 문제가 있습니다. 개발 여건상 중앙 서버에서 api key를 전달하기엔 서버 코딩이나 통신 등 현실적으로 너무 작업량이 많아지고, 이걸 코드 내에 string으로 저장해서 깃에 올리니, 민감한 정보가 공개적으로 저장되어 있으니 빨리 수정하고 메일이 왔었습니다. 이론적으로도 저게 그냥 아이디 비밀번호를 구글에다가 공개하는 거라 마찬가지인 셈이라, 그냥 평문으로 저장할 수는 없을 것 같습니다.

 저희가 협업을 해야 하고, 저게 핵심적인 기능이라 나중에 테스트할 때도 계속 firebase의 통신기능을 이용해야 할 텐데, 매번 api 키를 넣었다 뺐다 하는 방식으로 해야 하는 걸까요? 혹시 좋은 방법이 있을까 여쭤봅니다.

**Comment by shieldnet** [comment]
txt파일이나 json파일로 따로 빼서 관리하면 될 것 같습니다. github에는 .gitignore 처리해두고 관리하면 될 것 같습니다.

**Comment by RE-A** [comment]
REST API 이용하니까 api key 없이 URL 주소만으로 가능하네요. 이슈 닫겠습니다.
